/// Converts a list of `Namespace` values into a single Swift source file string.
public struct CodeGenerator: Sendable {

    // MARK: - Configuration

    public struct Configuration: Sendable {
        /// Root enum name that wraps all namespaces. Default: `i18n`.
        public let rootEnumName: String
        /// `.strings` / `.stringsdict` table name. Default: `Localizable`.
        public let tableName: String
        /// Bundle expression inserted verbatim. Default: `.main`.
        public let bundleExpression: String

        public init(
            rootEnumName: String = "i18n",
            tableName: String = "Localizable",
            bundleExpression: String = ".main"
        ) {
            self.rootEnumName = rootEnumName
            self.tableName = tableName
            self.bundleExpression = bundleExpression
        }
    }

    // MARK: - State

    private let configuration: Configuration

    public init(configuration: Configuration = .init()) {
        self.configuration = configuration
    }

    // MARK: - Generation

    /// Render all namespaces to a single `.swift` source string.
    public func generate(namespaces: [Namespace]) -> String {
        var lines: [String] = []

        lines += header()
        lines += rootEnumDeclaration()
        lines.append("")

        // Common always first, then the rest alphabetically
        let sorted = namespaces.sorted {
            if $0.name == "Common" { return true  }
            if $1.name == "Common" { return false }
            return $0.name < $1.name
        }
        for namespace in sorted {
            lines += namespaceExtension(namespace)
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private func header() -> [String] {
        [
            "// Auto-generated by SwiftL10n — do not edit.",
            "// swiftlint:disable all",
            "",
            "import Foundation",
            "",
        ]
    }

    private func rootEnumDeclaration() -> [String] {
        [
            "enum \(configuration.rootEnumName) {",
            "    fileprivate enum General {",
            "        static let table = \"\(configuration.tableName)\"",
            "        static let bundle = Bundle\(configuration.bundleExpression)",
            "    }",
            "}",
        ]
    }

    private func namespaceExtension(_ namespace: Namespace) -> [String] {
        var lines: [String] = []
        lines.append("extension \(configuration.rootEnumName) {")
        lines.append("    enum \(namespace.name) {")

        for string in deduplicated(namespace.strings) {
            let funcName = propertyName(for: string)
            let comment  = "\(namespace.name): \(string.context.displayName) — \(escaped(string.value))"
            lines.append("        /// \"\(escaped(string.value))\"")
            lines.append("        static func \(funcName)() -> String {")
            lines.append("            String(")
            lines.append("                localized: \"\(escaped(string.value))\",")
            lines.append("                table: General.table,")
            lines.append("                bundle: General.bundle,")
            lines.append("                comment: \"\(comment)\"")
            lines.append("            )")
            lines.append("        }")
            lines.append("")
        }

        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines
    }

    // MARK: - Deduplication

    /// When two strings produce the same function name (e.g. "Continue" and "Continue →"),
    /// keep the one with fewer decorative characters — the cleaner string is the localisation key.
    /// Preserves original detection order for the survivors.
    private func deduplicated(_ strings: [DetectedString]) -> [DetectedString] {
        // Skip interpolated strings — they're never generated
        let candidates = strings.filter { !$0.hasInterpolation }

        // For each function name, find the string with the fewest decorative chars
        var best: [String: DetectedString] = [:]
        for string in candidates {
            let name = propertyName(for: string)
            if let existing = best[name] {
                if decorativeCount(string.value) < decorativeCount(existing.value) {
                    best[name] = string
                }
            } else {
                best[name] = string
            }
        }

        // Emit in original order, one entry per name
        var emitted = Set<String>()
        return candidates.compactMap { string in
            let name = propertyName(for: string)
            guard !emitted.contains(name), best[name]?.value == string.value else { return nil }
            emitted.insert(name)
            return string
        }
    }

    /// Number of non-letter, non-digit, non-whitespace characters — a proxy for "decorative noise".
    private func decorativeCount(_ value: String) -> Int {
        value.filter { !$0.isLetter && !$0.isNumber && !$0.isWhitespace }.count
    }

    // MARK: - Naming Helpers

    func propertyName(for string: DetectedString) -> String {
        let words = string.value
            .components(separatedBy: .init(charactersIn: " \t\n-_.,;:!?()[]{}\"'→←↑↓•…"))
            .filter { !$0.isEmpty }
            .map { $0.filter(\.isLetter) }
            .filter { !$0.isEmpty }

        guard !words.isEmpty else { return "localizedString" }

        let base = words[0].lowercased()
            + words.dropFirst().map(\.localizedCapitalized).joined()

        let suffix = string.context.propertySuffix
        let name = suffix.isEmpty ? base : base + suffix
        return Self.swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    private static let swiftKeywords: Set<String> = [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
        "import", "init", "inout", "internal", "let", "open", "operator", "private",
        "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
        "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough",
        "for", "guard", "if", "in", "repeat", "return", "throw", "throws", "try", "where", "while",
        "as", "false", "is", "nil", "self", "super", "true", "any", "some",
        "convenience", "dynamic", "final", "get", "indirect", "lazy", "mutating",
        "nonmutating", "optional", "override", "postfix", "precedence", "prefix",
        "required", "set", "unowned", "weak", "willSet", "didSet",
    ]

    private func escaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
