/// Converts a list of `Namespace` values into a single Swift source file string.
public struct CodeGenerator: Sendable {

    // MARK: - Configuration

    public struct Configuration: Sendable {
        /// Root enum name that wraps all namespaces. Default: `i18n`.
        public let rootEnumName: String
        /// `.strings` / `.stringsdict` table name. Default: `Localizable`.
        public let tableName: String
        /// Bundle expression inserted verbatim. Default: `.main`.
        public let bundleExpression: String

        public init(
            rootEnumName: String = "i18n",
            tableName: String = "Localizable",
            bundleExpression: String = ".main"
        ) {
            self.rootEnumName = rootEnumName
            self.tableName = tableName
            self.bundleExpression = bundleExpression
        }
    }

    // MARK: - State

    private let configuration: Configuration

    public init(configuration: Configuration = .init()) {
        self.configuration = configuration
    }

    // MARK: - Generation

    /// Render all namespaces to a single `.swift` source string.
    ///
    /// - Parameters:
    ///   - namespaces: Freshly-detected namespaces from the current scan.
    ///   - preserved: Accessors recovered from a previously-generated file that
    ///     must survive regeneration (they are still referenced in source but
    ///     their literal has been migrated away). Within a namespace, a freshly
    ///     scanned string always wins over a preserved accessor with the same
    ///     function name. Preserved-only namespaces are emitted too.
    public func generate(namespaces: [Namespace], preserved: [PreservedAccessor] = []) -> String {
        var lines: [String] = []

        lines += header()
        lines += rootEnumDeclaration()
        lines.append("")

        let preservedByNamespace = Dictionary(grouping: preserved, by: \.namespace)
        let namespaceByName      = Dictionary(namespaces.map { ($0.name, $0) }, uniquingKeysWith: { first, _ in first })
        let allNames             = Set(namespaces.map(\.name)).union(preservedByNamespace.keys)

        // Common always first, then the rest alphabetically
        let sortedNames = allNames.sorted {
            if $0 == "Common" { return true  }
            if $1 == "Common" { return false }
            return $0 < $1
        }
        for name in sortedNames {
            lines += namespaceExtension(
                name:      name,
                strings:   namespaceByName[name]?.strings ?? [],
                preserved: preservedByNamespace[name] ?? []
            )
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private func header() -> [String] {
        [
            "// Auto-generated by SwiftL10n — do not edit.",
            "// swiftlint:disable all",
            "",
            "import Foundation",
            "",
        ]
    }

    private func rootEnumDeclaration() -> [String] {
        [
            "enum \(configuration.rootEnumName) {",
            "    fileprivate enum General {",
            "        static let table = \"\(configuration.tableName)\"",
            "        static let bundle = Bundle\(configuration.bundleExpression)",
            "    }",
            "}",
        ]
    }

    private func namespaceExtension(name: String, strings: [DetectedString], preserved: [PreservedAccessor]) -> [String] {
        var lines: [String] = []
        lines.append("extension \(configuration.rootEnumName) {")
        lines.append("    enum \(name) {")

        // Bare function names already emitted from the fresh scan — a preserved
        // accessor with the same name is skipped (the scan reflects the live value).
        var emitted = Set<String>()

        for string in deduplicated(strings) {
            let bare    = propertyNameBare(for: string)
            emitted.insert(bare)
            let escVal  = escaped(string.value)
            let comment = "\(name): \(string.context.displayName) — \(escVal)"
            lines += accessor(funcName: backticked(bare), escapedValue: escVal, escapedComment: comment)
        }

        for preservedAccessor in preserved where !emitted.contains(preservedAccessor.funcName) {
            emitted.insert(preservedAccessor.funcName)
            lines += accessor(
                funcName:       backticked(preservedAccessor.funcName),
                escapedValue:   preservedAccessor.escapedValue,
                escapedComment: preservedAccessor.escapedComment
            )
        }

        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines
    }

    /// Render one accessor's lines. Inputs are already source-escaped so that
    /// freshly-scanned strings and preserved accessors emit identically.
    private func accessor(funcName: String, escapedValue: String, escapedComment: String) -> [String] {
        [
            "        /// \"\(escapedValue)\"",
            "        static func \(funcName)() -> String {",
            "            String(",
            "                localized: \"\(escapedValue)\",",
            "                table: General.table,",
            "                bundle: General.bundle,",
            "                comment: \"\(escapedComment)\"",
            "            )",
            "        }",
            "",
        ]
    }

    // MARK: - Deduplication

    /// When two strings produce the same function name (e.g. "Continue" and "Continue →"),
    /// keep the one with fewer decorative characters — the cleaner string is the localisation key.
    /// Preserves original detection order for the survivors.
    private func deduplicated(_ strings: [DetectedString]) -> [DetectedString] {
        // Skip interpolated strings — they're never generated
        let candidates = strings.filter { !$0.hasInterpolation }

        // For each function name, find the string with the fewest decorative chars
        var best: [String: DetectedString] = [:]
        for string in candidates {
            let name = propertyName(for: string)
            if let existing = best[name] {
                if decorativeCount(string.value) < decorativeCount(existing.value) {
                    best[name] = string
                }
            } else {
                best[name] = string
            }
        }

        // Emit in original order, one entry per name
        var emitted = Set<String>()
        return candidates.compactMap { string in
            let name = propertyName(for: string)
            guard !emitted.contains(name), best[name]?.value == string.value else { return nil }
            emitted.insert(name)
            return string
        }
    }

    /// Number of non-letter, non-digit, non-whitespace characters — a proxy for "decorative noise".
    private func decorativeCount(_ value: String) -> Int {
        value.filter { !$0.isLetter && !$0.isNumber && !$0.isWhitespace }.count
    }

    // MARK: - Naming Helpers

    func propertyName(for string: DetectedString) -> String {
        backticked(propertyNameBare(for: string))
    }

    /// Function name without keyword backticking — used as the dedup/merge key.
    func propertyNameBare(for string: DetectedString) -> String {
        let words = string.value
            .components(separatedBy: .init(charactersIn: " \t\n-_.,;:!?()[]{}\"'→←↑↓•…"))
            .filter { !$0.isEmpty }
            .map { $0.filter(\.isLetter) }
            .filter { !$0.isEmpty }

        guard !words.isEmpty else { return "localizedString" }

        let base = words[0].lowercased()
            + words.dropFirst().map(\.localizedCapitalized).joined()

        let suffix = string.context.propertySuffix
        return suffix.isEmpty ? base : base + suffix
    }

    /// Wrap reserved Swift keywords in backticks so the generated identifier compiles.
    private func backticked(_ name: String) -> String {
        Self.swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    private static let swiftKeywords: Set<String> = [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func",
        "import", "init", "inout", "internal", "let", "open", "operator", "private",
        "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
        "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough",
        "for", "guard", "if", "in", "repeat", "return", "throw", "throws", "try", "where", "while",
        "as", "false", "is", "nil", "self", "super", "true", "any", "some",
        "convenience", "dynamic", "final", "get", "indirect", "lazy", "mutating",
        "nonmutating", "optional", "override", "postfix", "precedence", "prefix",
        "required", "set", "unowned", "weak", "willSet", "didSet",
    ]

    private func escaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
