/// Converts a list of `Namespace` values into a single Swift source file string.
///
/// Phase 1 skeleton — property names are derived mechanically from the raw string value.
/// Phase 2 will introduce semantic naming (context suffix, deduplication, conflict resolution).
///
/// Generated output shape:
/// ```swift
/// enum i18n {
///     fileprivate enum General { … }
/// }
/// extension i18n {
///     enum Settings {
///         static var deleteAccountButtonTitle: String { … }
///     }
/// }
/// ```
public struct CodeGenerator: Sendable {

    // MARK: - Configuration

    public struct Configuration: Sendable {
        /// Root enum name that wraps all namespaces. Default: `i18n`.
        public let rootEnumName: String
        /// `.strings` / `.stringsdict` table name. Default: `Localizable`.
        public let tableName: String
        /// Bundle expression inserted verbatim. Default: `.main`.
        public let bundleExpression: String

        public init(
            rootEnumName: String = "i18n",
            tableName: String = "Localizable",
            bundleExpression: String = ".main"
        ) {
            self.rootEnumName = rootEnumName
            self.tableName = tableName
            self.bundleExpression = bundleExpression
        }
    }

    // MARK: - State

    private let configuration: Configuration

    public init(configuration: Configuration = .init()) {
        self.configuration = configuration
    }

    // MARK: - Generation

    /// Render all namespaces to a single `.swift` source string.
    public func generate(namespaces: [Namespace]) -> String {
        var lines: [String] = []

        lines += header()
        lines += rootEnumDeclaration()
        lines.append("")

        for namespace in namespaces.sorted(by: { $0.name < $1.name }) {
            lines += namespaceExtension(namespace)
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Sections

    private func header() -> [String] {
        [
            "// Auto-generated by SwiftL10n — do not edit.",
            "// swiftlint:disable all",
            "",
            "import Foundation",
            "",
        ]
    }

    private func rootEnumDeclaration() -> [String] {
        [
            "enum \(configuration.rootEnumName) {",
            "    fileprivate enum General {",
            "        static let table = \"\(configuration.tableName)\"",
            "        static let bundle = Bundle\(configuration.bundleExpression)",
            "    }",
            "}",
        ]
    }

    private func namespaceExtension(_ namespace: Namespace) -> [String] {
        var lines: [String] = []
        lines.append("extension \(configuration.rootEnumName) {")
        lines.append("    enum \(namespace.name) {")

        for string in namespace.strings where !string.hasInterpolation {
            let propName = propertyName(for: string)
            lines.append("        static var \(propName): String {")
            lines.append("            String(")
            lines.append("                localized: \"\(escaped(string.value))\",")
            lines.append("                table: General.table,")
            lines.append("                bundle: General.bundle,")
            lines.append("                comment: \"\(namespace.name) \(string.context.displayName) — \(escaped(string.value))\"")
            lines.append("            )")
            lines.append("        }")
        }

        lines.append("    }")
        lines.append("}")
        lines.append("")
        return lines
    }

    // MARK: - Naming Helpers

    /// Phase 1: derive a camelCase identifier from the raw string value + context suffix.
    /// Phase 2 will add deduplication and collision resolution.
    func propertyName(for string: DetectedString) -> String {
        let words = string.value
            .components(separatedBy: .init(charactersIn: " \t\n-_.,;:!?()[]{}\"'"))
            .filter { !$0.isEmpty }
            .map { $0.filter(\.isLetter) }
            .filter { !$0.isEmpty }

        guard !words.isEmpty else { return "localizedString" }

        let base = words[0].lowercased()
            + words.dropFirst().map(\.localizedCapitalized).joined()

        let suffix = string.context.propertySuffix
        return suffix.isEmpty ? base : base + suffix
    }

    private func escaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
